In [3]:
import pandas as pd
import numpy as np

# 数据的导入
df = pd.read_csv('./data/employees.csv')
# 数据的导出
df = df.tail(5)
df.to_csv('./data/new.csv')

In [4]:
# json
import json

df = pd.read_json('./data/test.json')
with open('./data/test.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
df = pd.DataFrame(data['users'])
df

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [5]:
# 缺失值的处理
s = pd.Series([1, 2, np.nan, None, pd.NA])
df = pd.DataFrame([[1, pd.NA, 2], [2, 3, 5], [pd.NA, 4, 6]], columns=['第一列', '第二列', '第三列'])
# print(s)
# 查看是否是缺失值
print(s.isna())
print(s.isnull())
print(df.isna())
print(df.isnull())
# 查看缺失值的个数
print(s.isna().sum())
print(df.isna().sum())

0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
3
第一列    1
第二列    1
第三列    0
dtype: int64

In [6]:
# 剔除缺失值
print(s.dropna())
# 只要一条数据里有缺失值，就删除这条数据
print(df.dropna())
# 如果所有的值都是缺失值，才删除这条数据
print(df.dropna(how='all'))
# 至少有n个值不是缺失值，就保留
print(df.dropna(thresh=2))
# 删除一整列的记录
print(df.dropna(axis=1))
# 如果某列有缺失值，则删除这一行
print(df.dropna(subset=['第一列']))

0    1
1    2
dtype: object
  第一列 第二列  第三列
1   2   3    5
    第一列   第二列  第三列
0     1  <NA>    2
1     2     3    5
2  <NA>     4    6
    第一列   第二列  第三列
0     1  <NA>    2
1     2     3    5
2  <NA>     4    6
   第三列
0    2
1    5
2    6
  第一列   第二列  第三列
0   1  <NA>    2
1   2     3    5

In [7]:
# 填充缺失值
df = pd.read_csv('./data/weather_withna.csv')
df.tail()
# df.isna().sum(axis=0)
# 对缺失值填充
df.fillna({'temp_max': 20, 'wind': 2.5}).tail()
# 使用统计值填充
df.fillna(df[['temp_max', 'wind']].mean()).tail()
# 用前面的值填充，用后面的值填充: bfill()
df.ffill().tail()

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [8]:
# 重复数据处理
data = {
    'Name': ['Alice', 'Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 26, 30, 25, 35, 30],
    'City': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)
# 检测整条记录是否重复
df.duplicated()
# 根据指定的列去重，keep='last'：保留最后重复的数据
# df.drop_duplicates(subset=['Name'])
df.drop_duplicates(subset=['Name'], keep='last')

      Name  Age City
3    Alice   25   NY
4  Charlie   35   SF
5      Bob   30   LA

In [9]:
# 数据类型转换
df = pd.read_csv('./data/sleep.csv')
df['age'] = df['age'].astype('int16')
df.dtypes
df['gender'] = df['gender'].astype('category')
df.gender
# 映射数据
df['is_male'] = df['gender'].map({'Female': False, 'Male': True})
df.is_male

0       True
1      False
2       True
3       True
4       True
       ...
395    False
396    False
397    False
398    False
399     True
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [False, True]

In [10]:
# 数据重塑与变形
data = {
    'ID': [1, 2],
    'name': ['alice', 'bob'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
# df.T
# print(df)
# 宽表转换成长表
df2 = pd.melt(df, id_vars=['ID', 'name'], var_name='科目', value_name='分数')
df2.sort_values('name')
# print(df2)
# 长表转宽表
df3 = pd.pivot(df2, index=['ID', 'name'], columns='科目', values='分数')
# print(df3)

# 分列
data = {
    'ID': [1, 2],
    'name': ['alice smith', 'bob jack'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
df[['first', 'last']] = df['name'].str.split(' ', expand=True)

In [11]:
# 数据分箱
df = pd.read_csv('./data/employees.csv')
df1 = df.head(10)[['employee_id', 'salary']]
print(df1)
# bins=n：分成n段区间，起始值、结束值是所有数据的最小值、最大值
pd.cut(df1.salary, bins=2).value_counts()
# 自定义区间
df1['收入范围'] = pd.cut(df1.salary, bins=[0, 10000, 15000, 20000, 30000], labels=['低', '中', '高', '超高'])
# print(df1)
# 等频率分割
pd.qcut(df1.salary, 3).value_counts()

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [12]:
# 时间数据处理
# https://www.yuque.com/jyafoo/backend/dp6fygyw1s2gur3g#Hod9D

In [35]:
# 分组聚合
# df.groupby('分组的字段')['聚合的字段'].聚合函数()
df = pd.read_csv('./data/employees.csv')
df = df.dropna(subset=['department_id'])
df['department_id'] = df['department_id'].astype('int64')
# 计算不同部门的平均薪资
df.groupby('department_id').groups  # 查看分组情况
df.groupby('department_id').get_group(20)  # 查看具体的某个分组数据
df2 = df.groupby('department_id')[['salary']].mean().round(2)
df2 = df2.reset_index()
df2.sort_values('salary', ascending=False)

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [46]:
# 计算不同部门不同岗位的人的平均薪资
df2 = df.groupby(['department_id', 'job_id'])['salary'].mean()
df2 = df2.reset_index()
df2['salary'] = df2['salary'].round(1)
df2.sort_values('salary', ascending=False)

    department_id      job_id   salary
13             90     AD_PRES  24000.0
14             90       AD_VP  17000.0
1              20      MK_MAN  13000.0
11             80      SA_MAN  12200.0
16            100      FI_MGR  12000.0
18            110      AC_MGR  12000.0
4              30      PU_MAN  11000.0
10             70      PR_REP  10000.0
12             80      SA_REP   8396.6
17            110  AC_ACCOUNT   8300.0
15            100  FI_ACCOUNT   7920.0
8              50      ST_MAN   7280.0
5              40      HR_REP   6500.0
2              20      MK_REP   6000.0
9              60     IT_PROG   5760.0
0              10     AD_ASST   4400.0
6              50    SH_CLERK   3215.0
7              50    ST_CLERK   2785.0
3              30    PU_CLERK   2780.0