In [4]:
# 企鹅数据分析
# 1. 导入必要的库
import numpy as np
import pandas as pd

# 2. 导入数据
df = pd.read_csv('./data/penguins.csv')

In [8]:
# 3. 数据清洗
# 处理缺失值
df.dropna(inplace=True)  # inplace=True: 修改原数据

In [14]:
# 4. 数据特征的构造
df['sex'] = df['sex'].astype('category')
df['bill_radio'] = df['bill_length_mm'] / df['bill_depth_mm']
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_radio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767

In [23]:
# 5. 数据分析
# 数据分箱：把体重分为三个等级
df['mass_level'] = pd.cut(df['body_mass_g'], bins=3, labels=['低', '中', '高'])
df['mass_level'].value_counts()
# 按岛屿、性别分组分析
# df.groupby(['sex'])['body_mass_g'].mean()
# df.groupby(['sex'])['body_mass_g'].count()
df.groupby(['sex', 'island']).agg({
    'body_mass_g': ['mean', 'count']
})

                  body_mass_g
                         mean count
sex    island
Female Biscoe     4319.375000    80
       Dream      3446.311475    61
       Torgersen  3395.833333    24
Male   Biscoe     5104.518072    83
       Dream      3987.096774    62
       Torgersen  4034.782609    23

In [41]:
# 睡眠质量分析
import pandas as pd

df = pd.read_csv('./data/sleep.csv')
df.head(5)

# df.isna().sum()
# df['sleep_disorder'].value_counts()
df.drop(columns='sleep_disorder', inplace=True)

df['gender'] = df['gender'].astype('category')
df['occupation'] = df['occupation'].astype('category')
df['bmi_category'] = df['bmi_category'].astype('category')
df[['high', 'low']] = df['blood_pressure'].str.split('/', expand=True)
df.head(2)

# 睡眠质量的分箱
df['quality_level'] = pd.cut(df['sleep_quality'], bins=3, labels=['差', '中', '优'])
df['age_level'] = pd.cut(df['age'], bins=3, labels=['青少年', '中年', '老年'])
df.head(2)

# df['bmi_category'].value_counts()
# 根据不同的bmi分组，看睡眠质量是否有区别
df.groupby(['age_level', 'bmi_category']).agg({
    'sleep_duration': ['mean'],
    'sleep_quality': ['mean'],
    'stress_level': ['mean'],
})

                       sleep_duration sleep_quality stress_level
                                 mean          mean         mean
age_level bmi_category
青少年       Normal             8.100000      6.332000     4.860000
          Obese              8.250000      6.253448     5.534483
          Overweight         8.214286      6.171429     5.317460
          Underweight        7.603279      5.883607     5.426230
中年        Normal             7.422222      6.650000     4.944444
          Obese              7.805556      6.216667     5.888889
          Overweight         8.246154      5.956410     5.974359
          Underweight        8.497500      5.907500     5.750000
老年        Normal             7.420000      4.240000     4.200000
          Obese              7.900000      5.025000     8.000000
          Overweight         8.971429      6.285714     6.714286
          Underweight       10.500000      6.200000     6.000000